//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace evolution
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersAwards
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> AwardID { get; set; }
    
        public virtual Award Awards { get; set; }
        public virtual User Users { get; set; }
    }
}
